# Generated by Django 4.2.17 on 2025-01-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('product', '0002_remove_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_products', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('brands', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='product.category')),
                ('products', models.ManyToManyField(blank=True, to='product.product')),
                ('subcategories', models.ManyToManyField(blank=True, to='product.subcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, related_name='product_offers', to='product.category')),
                ('products', models.ManyToManyField(blank=True, related_name='product_offers', to='product.product')),
                ('subcategories', models.ManyToManyField(blank=True, to='product.subcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='vendor.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='CountryOrigin',
        ),
    ]
