# Generated by Django 4.2.17 on 2025-01-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_orderoffer_productoffer_delete_countryorigin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderoffer',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='orderoffer',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='orderoffer',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='subcategories',
        ),
    ]
