# Generated by Django 5.1.4 on 2025-01-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_image'),
        ('product', '0003_orderoffer_productoffer_delete_countryorigin'),
    ]

    operations = [
    ]
