# Generated by Django 5.1.4 on 2025-01-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_merge_20250106_2138'),
        ('product', '0004_remove_orderoffer_brands_and_more'),
    ]

    operations = [
    ]
