# Generated by Django 4.2.17 on 2025-01-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_merge_20250106_2138'),
        ('product', '0004_remove_orderoffer_brands_and_more'),
    ]

    operations = [
    ]
