# Generated by Django 4.2.17 on 2025-01-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_merge_20250107_1515'),
        ('product', '0005_merge_20250108_1831'),
    ]

    operations = [
    ]
