# Generated by Django 4.2.17 on 2025-01-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_merge_20250108_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
