# Generated by Django 4.2.17 on 2025-02-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exc1_offer_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exc1_offer', to='product.product')),
                ('exc2_offer_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exc2_offer', to='product.product')),
                ('exc3_offer_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exc3_offer', to='product.product')),
                ('slide1_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide1', to='product.product')),
                ('slide2_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide2', to='product.product')),
                ('slide3_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide3', to='product.product')),
            ],
        ),
    ]
