# Generated by Django 5.1.5 on 2025-02-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
